### ISSUE TITLE
is there any package called shinyapps

### ISSUE THREAD

**Issue by chekavjit** [hturner/shiny-demos#1]
i cannot find the package "shinytools"  even if i try to install it ...plzzz help me out

apps under the below link are using  library(shinytools) ...i tried the same app..but it is not running ..it shows the error 
Error in func() : could not find function "plotLoss"
Error in library(shinytools) : there is no package called ‘shinytools’

link ::https://github.com/hturner/shiny-demos

.

**Comment by hturner** [comment]
I have updated the README with instructions for installing all required packages - let me know if you still have any issues.

**Comment by hturner** [comment]
I should say let me know if this solves this issue, so I can mark it as closed.

**Comment by chekavjit** [comment]
hiii,

Thank you soo much...now app is running on my machine..thank u

**Comment by chekavjit** [comment]
hi,

I am trying to develop a shiny app...but it contains some error..i will be
highly grateful if you look into the matter.

I have attached by code.
the error i am getting is  : " cannot coerce class ""lm"" to a data.frame"
 , when i click on the download button
i want to download the 4 tables in which appear on right side when i check
the checkboxes .

**Comment by hturner** [comment]
I cannot see your code - I do not think it is possible to attach anything other than images here. I would guess from the error that the code is trying to save the fitted model object via `write.csv` or similar, when what you want is to save the 4 tables to file. If the tables are created on-the-fly you may need to assign them a name, e.g.

```
tab <- data.frame(coef = coef(mod))
```

Then use this name in the call to `write.csv` or whatever is being used in `downloadHandler`.

This discussion has gone beyond the scope of the original issue, so if you still need help, try the forums mentioned here:
http://shiny.rstudio.com/help/
